### ISSUE TITLE
Invalidation not working properly (on Chrome only perhaps)

### ISSUE THREAD

**Issue by samskivert** [tfwdev/platform#2]
Clicking checkboxes in the todo MVC demo is not updating them until a second invalidation has happened.

**Comment by samskivert** [comment]
Actually looks like maybe the checkbox label invalidation is not being processed properly. Or there's a separate bug relating to that because in some cases it's not moving to the new position when a list entry is deleted and the whole todo row moves up.

**Comment by ey6es** [comment]
I was interested in this because I noticed it happening and thought it was due to a bug in the dirty region tracking.  To reproduce: load the UI demo, select Completed, then select All.  The checkboxes then don't update (including their cursors), then start to update again after you've pressed some more buttons.

Anyway, if that's what this was, then I fixed it (it was a bug in List).

**Comment by samskivert** [comment]
Awesome, thanks!
